theme: jekyll-theme-minimal
twitter:
    username: takpika0308
defaults:
  - scope:
        path: ""
    values:
        image:
            path: /NicoClip/img/logo.png
            height: 1280
            width: 1280
